# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[󰞸](bold yellow) \
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$fill\
$cmd_duration\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

# Configure the time module (optional: customize format/style)
[time]
disabled = false
format = '[\[$time\]]($style) '
style = "yellow"

# Configure the command duration module (optional: customize format/threshold)
[cmd_duration]
disabled = false
min_time = 2000 # Only show for commands > 2 seconds
format = '[◷ $duration]($style) '
style = "bright-black"
